name: Sync Subrepos

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history for subtree operations

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to montagne-api
        run: |
          if ! git diff --quiet HEAD^ HEAD -- montagne-api/; then
            echo "Changes detected in montagne-api. Pushing..."
            git subtree push --prefix=montagne-api https://x-access-token:${{ secrets.GH_PAT }}@github.com/achaayb/montagne-api.git main
          else
            echo "No changes in montagne-api. Skipping push."
          fi

      - name: Push to montagne-proxy
        run: |
          if ! git diff --quiet HEAD^ HEAD -- montagne-proxy/; then
            echo "Changes detected in montagne-proxy. Pushing..."
            git subtree push --prefix=montagne-proxy https://x-access-token:${{ secrets.GH_PAT }}@github.com/achaayb/montagne-proxy.git main
          else
            echo "No changes in montagne-proxy. Skipping push."
          fi

      - name: Push to montagne-dashboard
        run: |
          if ! git diff --quiet HEAD^ HEAD -- montagne-dashboard/; then
            echo "Changes detected in montagne-dashboard. Pushing..."
            git subtree push --prefix=montagne-dashboard https://x-access-token:${{ secrets.GH_PAT }}@github.com/achaayb/montagne-dashboard.git main
          else
            echo "No changes in montagne-dashboard. Skipping push."
          fi

      - name: Push to montagne-worker
        run: |
          if ! git diff --quiet HEAD^ HEAD -- montagne-worker/; then
            echo "Changes detected in montagne-worker. Pushing..."
            git subtree push --prefix=montagne-worker https://x-access-token:${{ secrets.GH_PAT }}@github.com/achaayb/montagne-worker.git main
          else
            echo "No changes in montagne-worker. Skipping push."
          fi
